### PR TITLE
Switch to posix/spawn

### PR DESCRIPTION
**Pull request by akozl**
This change is [Reviewable](https://reviewable.io/reviews/zaiusinc/diffy/1)

### CODE REVIEW

**Review by derekharmel — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/diffy/1#-:-MYQ0q_d-V1hpT4pf9Sr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @akozl, @ianpf, and @Lomey)

___
*[README.md, line 7 at r1](https://reviewable.io/reviews/zaiusinc/diffy/1#-MYQ0bGRA-cxyUQp6qtt:-MYQ0bGRA-cxyUQp6qtu:bpaz73p) ([raw file](https://github.com/zaiusinc/diffy/blob/e998e69aa5e7e60bf4a9d6898f68dc1438c2c670/README.md#L7)):*
> ```Markdown
> diff = Open3.popen3(diff_bin, *(diff_options + @paths)) { |i, o, e| o.read }
> ```
> deadlocks f the program generates too much output on stderr
> ```

I think the `f` here is a typo, but it's an amusing one.

**Review by Lomey — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/diffy/1)* status: all files reviewed, 1 unresolved discussion (waiting on @akozl and @ianpf)

**Review by Lomey — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/diffy/1)* status: all files reviewed, 1 unresolved discussion (waiting on @akozl and @ianpf)

**Review by akozl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/diffy/1)* status: all files reviewed, 1 unresolved discussion (waiting on @derekharmel and @ianpf)

___
*[README.md, line 7 at r1](https://reviewable.io/reviews/zaiusinc/diffy/1#-MYQ0bGRA-cxyUQp6qtt:-MYdISsP1aNjW_WCnS3b:b-896fix) ([raw file](https://github.com/zaiusinc/diffy/blob/e998e69aa5e7e60bf4a9d6898f68dc1438c2c670/README.md#L7)):*
<details><summary><i>Previously, derekharmel (Derek Harmel) wrote…</i></summary><blockquote>

I think the `f` here is a typo, but it's an amusing one.
</blockquote></details>

Done.

**Review by derekharmel — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/diffy/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ianpf)

**Pull request merged**
